name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'  # Ensure submodules (if any) are checked out

    - name: Set up Environment
      run: |
        brew update
        brew install rubberband
        # Optional: Install any other dependencies here

    - name: Show Directory Structure
      run: ls -R # helpful for debugging

    - name: Remove existing AudioUnitSDK (if present)
      run: rm -rf AudioUnitSDK # important

    - name: Clone AudioUnitSDK
      run: git clone https://github.com/apple/AudioUnitSDK.git

    - name: Configure CMake
      run: |
        cd build
        cmake -DCMAKE_INCLUDE_PATH="${GITHUB_WORKSPACE}/AudioUnitSDK/include" ..

    - name: Build
      run: |
        cd build
        make

    - name: Create Artifact Directory
      run: mkdir -p ./build/Release

    - name: Find AU Component
      run: |
        find ./build -name "PolyphonicPitchShifter.component" -path "*Release*" -exec cp {} ./build/Release \;

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AudioUnitComponent
        path: ./build/Release/PolyphonicPitchShifter.component
