name: Build AudioUnit Plugin
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest # Use a macOS runner as required for AudioUnits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-build
          
      - name: Install Build Dependencies
        run: |
          brew update
          brew install libsndfile libsamplerate cmake ninja ccache
          
      - name: Show Directory Structure
        run: |
          echo "Workspace directory structure:"
          ls -R ${{ github.workspace }}
          
      - name: Clone AudioUnitSDK
        run: |
          rm -rf ${{ github.workspace }}/AudioUnitSDK
          git clone --depth 1 https://github.com/apple/AudioUnitSDK.git ${{ github.workspace }}/AudioUnitSDK
          
      - name: Cache RubberBand
        id: cache-rubberband
        uses: actions/cache@v3
        with:
          path: /usr/local/include/rubberband
          key: ${{ runner.os }}-rubberband-22may
          
      - name: Clone and Build RubberBand
        if: steps.cache-rubberband.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://github.com/breakfastquay/rubberband.git ${{ github.workspace }}/rubberband
          cd ${{ github.workspace }}/rubberband
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -GNinja
          ninja
          sudo ninja install
          
      - name: Configure CMake
        run: |
          # Set up environment variables for compiler cache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          
          # Clean and create build directory
          rm -rf build
          mkdir -p build
          cd build
          
          # Run CMake with Ninja generator for faster builds
          cmake \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CXX_FLAGS="-I${{ github.workspace }}/AudioUnitSDK/include -O3" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            ..
            
      - name: Build Plugin
        run: |
          cd build
          ninja
          
      - name: Create Artifact Directory
        run: mkdir -p build/Release
        
      - name: Find and Copy AU Component
        run: |
          # Find the built .component file and copy it to the Release directory
          find build -name "PolyphonicPitchShifter.component" \
            -type d -exec cp -R {} build/Release/ \;
          
      - name: Validate AudioUnit
        run: |
          # Verify the AudioUnit can be validated by macOS
          /usr/bin/auval -v aumu PPSH YourCo
          
      - name: Ad-hoc Code Sign AU Component
        run: |
          codesign --force --deep --sign - build/Release/PolyphonicPitchShifter.component
          
      - name: Upload AudioUnit Component Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioUnitComponent
          path: build/Release/PolyphonicPitchShifter.component
          if-no-files-found: error