name: macOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up project
        run: |
          mkdir -p output
          echo "Dummy artifact contents" > output/result.txt

      - name: Try standard artifact upload
        id: upload_standard
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: result-artifact
          path: output/result.txt

      - name: Fallback to GitHub CLI if upload failed
        if: steps.upload_standard.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Standard artifact upload failed — using gh CLI fallback."

          TAG_NAME="ci-fallback-artifacts"
          RELEASE_NAME="CI Artifact Fallback"
          FILE="output/result.txt"

          # Ensure release exists or create draft release
          if ! gh release view "$TAG_NAME" &>/dev/null; then
            gh release create "$TAG_NAME" "$FILE" \
              --title "$RELEASE_NAME" \
              --notes "Fallback artifact upload via gh CLI" \
              --draft
          else
            gh release upload "$TAG_NAME" "$FILE" --clobber
          fi

          echo "Fallback artifact uploaded to draft release
