name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Environment
        run: |
          brew update
          brew install rubberband

      - name: Show Directory Structure
        run: ls -R

      - name: Remove existing AudioUnitSDK (if present)
        run: rm -rf AudioUnitSDK

      - name: Clone AudioUnitSDK
        run: git clone https://github.com/apple/AudioUnitSDK.git

      - name: Debug AudioUnitSDK Contents
        run: ls -R AudioUnitSDK

      - name: Configure CMake
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INCLUDE_PATH="${GITHUB_WORKSPACE}/AudioUnitSDK/AudioUnitSDK/AUBase" \
                ..

      - name: Build
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)

      - name: Create Artifact Directory
        run: mkdir -p build/Release

      - name: Find AU Component
        run: |
          find build -name "PolyphonicPitchShifter.component" \
               -path "*Release*" \
               -exec cp -R {} build/Release/ \;

      - name: Ad-hoc Code Sign AU Component
        run: |
          codesign --force --deep --sign - build/Release/PolyphonicPitchShifter.component

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioUnitComponent
          path: build/Release/PolyphonicPitchShifter.component
          if-no-files-found: error
